[M4] combined updates after review
filecoin-project/filecoin-solidity pull request #64
Opened 2024-06-18 08:33 UTC by wertikalk

Contains changes requested from PRs: #54  and #56.

#### Summary:
- Unused vars. in `datacap.test.sol` removed
- Calibnet tests passing 
  - issue was the RPC, and also not enough wait time after tx broadcast
- Localhost network (`anvil` or `npx hardhat node`) added
  - used for debugging things that can run on common EVM chains

2024-06-21 19:17 UTC, snissn commented
i switched the merge to target master and i'm pushing an empty commit to try to trigger the CI

2024-06-21 22:33 UTC, snissn requested changes
For approval I'd like to replicate and see the following tests pass: 

- [x] forge tests
- [x] rust tests
- [ ] localhost tests
- [ ] calibnet test

The forge and rust tests are passing for me but I cannot get the localhost and calibnet tests to all pass.

we have a conversation going on slack regarding the calibnet test for the account test needing the private key. For the local test I am seeing the following:

```# make test_hh_localnet
./lib-dev/dev-env/5_test-run-localnet.sh
Localnet setup done - Running tests ...


  Account Test
    ✔ Test 1: Integration test port (63401ms)

  Address Test
Deploying contracts... (AddressTest)
    1) Test 1: Integration test port
DBG: (Test 1: Integration test port) :::: 
	Deploying contracts... (account)


  BigInt Test
Deploying contracts... (BigIntsTest)
    2) Test 1: Integration test port
DBG: (Test 1: Integration test port) :::: 
	Deploying contracts... (account)


  CborDecode Test
    ✔ Test 1: Integration test port (52839ms)

  Datacap Test
    ✔ Test 1: Integration test port (63138ms)

  Deserialize Params Test
Deploying contracts... (DeserializeParamsTest)
    ✔ Test 1: Integration test port (52856ms)

  Leb128 Test
    ✔ Test 1: Integration test port

  Market Tests
    ✔ Test 1: Basic Deal Flow (109939ms)

  Market Cbot Test
Deploying contracts... (MarketCBORTest)
    3) Test 1: Integration test port
DBG: (Test 1: Integration test port) :::: 
	Deploying contracts... (account)

	Deploying contracts... (CborDecodeTest)

	Deploying contracts... (DataCapApiTest)

	{"pDatacapAddr":"t410f3zg5mijonap3yf2ju7dm2rwvpdxl7op4c7n33dq"}

	calling 'name'

	calling 'symbol'

	calling 'total_supply'

	calling 'balance'

	calling 'allowance'


  Power Test
    4) Test 1: Integration test port
DBG: (Test 1: Integration test port) :::: 
	Deploying contracts... (account)

	Deploying contracts... (CborDecodeTest)

	Deploying contracts... (DataCapApiTest)

	{"pDatacapAddr":"t410f3zg5mijonap3yf2ju7dm2rwvpdxl7op4c7n33dq"}

	calling 'name'

	calling 'symbol'

	calling 'total_supply'

	calling 'balance'

	calling 'allowance'

	Deploying contracts... (PowerApiTest)


  Precompiles Test
    ✔ Test 1: Integration test port (43238ms)

  Send Test
    5) Test 1: Integration test port
DBG: (Test 1: Integration test port) :::: 
	Deploying contracts... (account)

	Deploying contracts... (CborDecodeTest)

	Deploying contracts... (DataCapApiTest)

	{"pDatacapAddr":"t410f3zg5mijonap3yf2ju7dm2rwvpdxl7op4c7n33dq"}

	calling 'name'

	calling 'symbol'

	calling 'total_supply'

	calling 'balance'

	calling 'allowance'

	Deploying contracts... (PowerApiTest)

	Deploying contracts... (PrecompilesApiTest)

	Deploying contracts... (SendApiTest)


  Verifreg Test
    ✔ Test 1: Integration test port (83468ms)

  Market Tests (Beacon)
    ✔ Test 1: Basic Deal Flow with Beacon Proxy Upgrade (125990ms)

  Market Tests (Transparent)
    ✔ Test 1: Basic Deal Flow with Transparent Proxy Upgrade (130691ms)

  Market Tests (UUPS)
    ✔ Test 1: Basic Deal Flow with UUPS Proxy Upgrade (115076ms)


  11 passing (16m)
  5 failing

  1) Address Test
       Test 1: Integration test port:
     Error: could not coalesce error (error={ "code": 1, "message": "failed to look up actor state nonce: resolution lookup failed (t410flhj4hu5a64fa3futegri35t6naug6cr3mdzmdii): resolve address t410flhj4hu5a64fa3futegri35t6naug6cr3mdzmdii: actor not found: validation failure" }, payload={ "id": 9, "jsonrpc": "2.0", "method": "eth_sendRawTransaction", "params": [ "0x02f904e58401df5e768083018bfd83018cc58502540be4008080b90488608060405234801561001057600080fd5b50610468806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063a0a8664714610030575b600080fd5b61003861003a565b005b60016000610047826100d7565b90507f49d03a195e239b52779866b33024210fc7dc66e9c2998975c0aa45c1702549d5816000015180519060200120146100d35760405162461bcd60e51b815260206004820152602360248201527f273127206163746f724944206973206e6f742072657475726e696e672027303060448201526230312760e81b606482015260840160405180910390fd5b5050565b60408051602081019091526060815260006100f18361012a565b60408051602081018252825192935091829161011191600091840161037a565b60408051601f1981840301815291905290529392505050565b6040805180820190915260608152600060208201525b6701ffffffffffffff600783901c1691607f16600083900361016d576101668282610181565b5050919050565b61017a8260808317610181565b5050610140565b60408051808201909152606081526000602082015282515160006101a68260016103d3565b9050846020015182106101c7576101c7856101c28360026103e6565b6101ed565b84516020838201018581535080518211156101e0578181525b5084925050505b92915050565b81516101f9838361020a565b506102048382610281565b50505050565b60408051808201909152606081526000602082015261022a6020836103fd565b156102525761023a6020836103fd565b61024590602061041f565b61024f90836103d3565b91505b60208084018390526040518085526000815290818401018181101561027657600080fd5b604052509192915050565b6040805180820190915260608152600060208201526102a2838384516102a9565b9392505050565b60408051808201909152606081526000602082015282518211156102cc57600080fd5b83515160006102db84836103d3565b905085602001518111156102f8576102f8866101c28360026103e6565b855180518382016020019160009180851115610312578482525b505050602086015b6020861061035257805182526103316020836103d3565b915061033e6020826103d3565b905061034b60208761041f565b955061031a565b51815160001960208890036101000a0190811690199190911617905250849150509392505050565b6001600160f81b0319831681528151600090815b818110156103ab576020818601810151600186840101520161038e565b50600092016001019182525092915050565b634e487b7160e01b600052601160045260246000fd5b808201808211156101e7576101e76103bd565b80820281158282048414176101e7576101e76103bd565b60008261041a57634e487b7160e01b600052601260045260246000fd5b500690565b818103818111156101e7576101e76103bd56fea26469706673582212208b306a6330db42863ecc8b13055c3abb92d908654f3208c0284187b5d30b08e564736f6c63430008120033c001a05b82944b33a04883a21dbcc9c755d261d30670ee6131387f82effdcc4cd9879da06140499fc3d086945c5f2b693708b1ab8d51d32761426da1bc3d1b8500a0cb81" ] }, code=UNKNOWN_ERROR, version=6.12.1)
      at makeError (node_modules/ethers/src.ts/utils/errors.ts:694:21)
      at JsonRpcProvider.getRpcError (node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:1049:25)
      at /var/lib/fil-sol/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:563:45
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  2) BigInt Test
       Test 1: Integration test port:
     Error: could not coalesce error (error={ "code": 1, "message": "failed to look up actor state nonce: resolution lookup failed (t410fzyrzttara2jvr43ryrusmgwcimcchq56kyhcsmi): resolve address t410fzyrzttara2jvr43ryrusmgwcimcchq56kyhcsmi: actor not found: validation failure" }, payload={ "id": 9, "jsonrpc": "2.0", "method": "eth_sendRawTransaction", "params": [ "0x02f930ef8401df5e768083030890830309588502540be4008080b93092608060405234801561001057600080fd5b50613072806100206000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c806391a2b35314610067578063a7579d7a14610071578063c91a35af14610079578063cc15d40114610081578063ed98a8d414610089578063f807127b14610091575b600080fd5b61006f610099565b005b61006f610514565b61006f610c8c565b61006f61131e565b61006f6117b9565b61006f611cc9565b6040805180820190915260608152600060208201526100b860ff612300565b90507fe08ec2af2cfc251225e1968fd6ca21e4044f129bffa95bac3503be8bdb30a3678160000151805190602001201461010d5760405162461bcd60e51b815260040161010490612a4e565b60405180910390fd5b60208101511561012f5760405162461bcd60e51b815260040161010490612a7e565b61013a61ffff612300565b90507f3c2d8cd2b72f4d773761fded626d1882655d749460170d3c9023662f315a9d50816000015180519060200120146101865760405162461bcd60e51b815260040161010490612ab5565b6020810151156101a85760405162461bcd60e51b815260040161010490612a7e565b6101b462ffffff612300565b90507f9e7e9bd43817d5a918735ca8963a539baf6c7aa7cd9a3db2b1d55a811f31ca3e816000015180519060200120146102005760405162461bcd60e51b815260040161010490612aec565b60208101511561022257604051 [...]

2024-06-24 14:34 UTC, wertikalk commented
@snissn the test issues :
 >Error: could not coalesce error (error={ "code": 1, "message": "failed to look up actor state nonce: resolution lookup failed (t410flhj4hu5a64fa3futegri35t6naug6cr3mdzmdii): resolve address t410flhj4hu5a64fa3futegri35t6naug6cr3mdzmdii: actor not found: validation failure" }, payload={ "id": 9, "jsonrpc": "2.0", "method": "eth_sendRawTransaction", "params": [ "..." ] }, code=UNKNOWN_ERROR, version=6.12.1)

were due to the filecoin delayed execution model as some contracts were not included in the chain's state once their methods were called, and so the `failed to look up actor state nonce` happened - pushed the fix.

2024-06-25 00:34 UTC, snissn commented
Localhost tests are passing on the latest commit for me :+1: I just need the calibnet PK 

```
# make test_hh_localnet
./lib-dev/dev-env/5_test-run-localnet.sh
Localnet setup done - Running tests ...


  Account Test
    ✔ Test 1: Integration test port (99399ms)

  Address Test
Deploying contracts... (AddressTest)
    ✔ Test 1: Integration test port (85050ms)

  BigInt Test
Deploying contracts... (BigIntsTest)
    ✔ Test 1: Integration test port (62815ms)

  CborDecode Test
    ✔ Test 1: Integration test port (85052ms)

  Datacap Test
    ✔ Test 1: Integration test port (99409ms)

  Deserialize Params Test
Deploying contracts... (DeserializeParamsTest)
    ✔ Test 1: Integration test port (80918ms)

  Leb128 Test
    ✔ Test 1: Integration test port

  Market Tests
    ✔ Test 1: Basic Deal Flow (174164ms)

  Market Cbot Test
Deploying contracts... (MarketCBORTest)
    ✔ Test 1: Integration test port (84769ms)

  Power Test
    ✔ Test 1: Integration test port (62975ms)

  Precompiles Test
    ✔ Test 1: Integration test port (67492ms)

  Send Test
    ✔ Test 1: Integration test port (121213ms)

  Verifreg Test
    ✔ Test 1: Integration test port (139675ms)

  Market Tests (Beacon)
    ✔ Test 1: Basic Deal Flow with Beacon Proxy Upgrade (202249ms)

  Market Tests (Transparent)
    ✔ Test 1: Basic Deal Flow with Transparent Proxy Upgrade (202056ms)

  Market Tests (UUPS)
    ✔ Test 1: Basic Deal Flow with UUPS Proxy Upgrade (180309ms)


  16 passing (29m)
```

2024-07-01 09:28 UTC, snissn approved these changes
Hi! I want to merge this PR as is but I still have some minor nit pick questions about the values here. For F3_ADDR can we remove the need for a hard coded value here? If the only reason that it is needed is the calibration Address test, can we update the code in that test to not require a fixed hard coded Address?

2024-07-01 09:28 UTC, snissn commented on .env.example
> +# Generated dummy F3-type account on Calibration network using Lotus CLI
Can you include a recipe/methodology for how to specifically create these values? Is it specifically any f3 account that you fund? Just the lotus commands would be good.

2024-07-01 09:28 UTC, merged